version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.09.0-ce-git
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.09.0-ce
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache build-base mercurial musl-dev openssl git gcc go
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/app.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/app.tar | true
      - run:
          name: Build application Docker image
          command: |
            cd $(cat LATEST)
            docker version
            docker build --cache-from=app -t app .
      - run:
          name: Get Docker image size
          command: |
            mkdir /tmp/artifacts;
            docker images --format "{{.Size}}" app > /tmp/artifacts/size;
      - store_artifacts:
          path: /tmp/artifacts
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/app.tar app
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/app.tar
      - run:
          name: Tests start kafka
          command: |
            docker run -d \
                       --name kafka \
                       -p 9092:9092 \
                       -e KAFKA_ADVERTISED_HOST_NAME=localhost \
                       -e KAFKA_CREATE_TOPICS="test-topic:1:1" app
      - run:
          name: Tests get deps
          command: |
            set -x
            export GOPATH=/go
            go get -u github.com/Shopify/sarama/tools/kafka-console-consumer
            go get -u github.com/Shopify/sarama/tools/kafka-console-producer
      - run:
          name: Test consumer
          command: /go/bin/kafka-console-consumer --bootstrap-server localhost:9092 --topic test-topic > kafka.out || true

      - run:
          name: Test producer
          command: |
            echo shrinky-dinks | /go/bin/kafka-console-producer --topic test-topic --broker-list localhost:9092 || true
            grep -q "shrinky-dinks" kafka.out
